// Pre-computed outputs for regression testing.
// These were generated by running the simulation with CANONICAL_CONFIG (seed=42, 100 trials).
// If simulation math changes intentionally, update these values and document why.

export const CANONICAL_SEED_42_FIRST_10_VALUES = [
  0.7667527487687767,
  0.4355985574353486,
  0.6601462752930820,
  0.5562838965654373,
  0.9017382543161512,
  0.2743902882467657,
  0.1352499742526561,
  0.9583283156342804,
  0.8018538534991443,
  0.3361723420396447,
];

// P50 annual revenue for year 1, canonical config (approximate - within 5%)
// Update this if simulation logic changes intentionally
export const CANONICAL_YEAR1_P50_APPROX = 38000; // ~$38k/year for normal log-normal params
